# Load default processing options
imports:
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Processing.yaml" }
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml" }
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml" }

# Minimal configuration for the editor
editor:
  config:

    stylesSet: []

    format_tags: "p;h1;h2;h3"

    toolbarGroups:
      - { name: basicstyles, groups: [ basicstyles, cleanup ] }
      - { name: clipboard, groups: [ clipboard, undo ] }
      - { name: editing, groups: [ find, selection, spellchecker, editing ] }
      - { name: links, groups: [ links ] }
      - { name: insert, groups: [ insert ] }
      - { name: forms, groups: [ forms ] }
      - { name: tools, groups: [ tools ] }
      - { name: others, groups: [ others ] }
      - "/"
      - { name: paragraph, groups: [ list, indent, blocks, align, bidi, paragraph ] }
      - { name: styles, groups: [ styles ] }
      - { name: document, groups: [ mode, document, doctools ] }
      - { name: about, groups: [ about ] }
      - { name: colors, groups: [ colors ] }

    removeButtons:
      - Anchor
      - Underline
      - Strike
      - Scayt
      - Italic
      - Outdent
      - Indent
      - About
