base: 'https://www.lmr-nrw.de/'
baseVariants:
  -
    base: 'http://local.lmr-nrw.de/'
    condition: 'getenv("TYPO3_CONTEXT") == "Development"'
  -
    base: 'https://lmr-nrw.failx.de'
    condition: 'getenv("TYPO3_CONTEXT") == "Production/Staging"'
errorHandling: {  }
languages:
  -
    title: Deutsch
    enabled: true
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-DE
    direction: ''
    flag: de
    languageId: '0'
rootPageId: 118
routes: {  }
websiteTitle: ''
