# EXT:lmr_nrw/Configuration/RTE/Default.yaml
# CKEditor 5 configuration for TYPO3 13
imports:
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Processing.yaml" }
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml" }
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml" }

editor:
  config:
    contentsCss:
      - "EXT:rte_ckeditor/Resources/Public/Css/contents.css"
      - "EXT:lmr_nrw/Resources/Public/StyleSheet/rte.css"

    toolbar:
      items:
        - style
        - heading
        - '|'
        - bold
        - italic
        - underline
        - strikethrough
        - subscript
        - superscript
        - softhyphen
        - '|'
        - bulletedList
        - numberedList
        - blockQuote
        - '|'
        - alignment
        - '|'
        - link
        - '|'
        - insertTable
        - horizontalLine
        - specialCharacters
        - '|'
        - findAndReplace
        - removeFormat
        - '|'
        - undo
        - redo
        - '|'
        - sourceEditing

    heading:
      options:
        - { model: 'paragraph', title: 'Paragraph' }
        - { model: 'heading2', view: 'h2', title: 'Heading 2' }
        - { model: 'heading3', view: 'h3', title: 'Heading 3' }
        - { model: 'heading4', view: 'h4', title: 'Heading 4' }
        - { model: 'heading5', view: 'h5', title: 'Heading 5' }

    style:
      definitions:
        - { name: "Liste mit Kreiseln", element: "ul", classes: ['list-circle'] }
        - { name: "Liste mit Häkchen", element: "ul", classes: ['list-check'] }

    alignment:
      options:
        - { name: 'left', className: 'text-left' }
        - { name: 'center', className: 'text-center' }
        - { name: 'right', className: 'text-right' }
        - { name: 'justify', className: 'text-justify' }

    table:
      defaultHeadings: { rows: 1 }
      contentToolbar:
        - tableColumn
        - tableRow
        - mergeTableCells
        - tableProperties
        - tableCellProperties

buttons:
  link:
    properties:
      class:
        allowedClasses: 'btn btn-primary,btn btn-secondary'

classes:
  'btn btn-primary':
    name: 'Button Primary (Rot)'
  'btn btn-secondary':
    name: 'Button Secondary (Grau)'

processing:
  allowTags:
    - s
    - u
