name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php-versions: ['7.4']

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, intl
        tools: composer:v2

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.composer/cache
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install dependencies
      run: composer require -q deployer/deployer:~6.4 deployphp/recipes:~6.2

    - name: Setup SSH and known hosts
      env:
        PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
      run: |
        mkdir ~/.ssh
        echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan oc-vm87.riconnect.de >> ~/.ssh/known_hosts

    - name: Start SSH agent and add key
      run: |
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa

    - name: Deploy to staging
      if: "!startsWith(github.ref, 'refs/tags/')"
      run: vendor/bin/dep -f./.deployer/config.php deploy staging

    - name: Deploy to live
      if: startsWith(github.ref, 'refs/tags/')
      run: vendor/bin/dep -f./.deployer/config.php deploy prod

    - name: Send email notification
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: "GitHub Actions Build: ${{ github.repository }} - ${{ github.ref }}"
        body: Build result of ${{ github.repository }} (${{ github.ref }}) - ${{ job.status }}.
        to: info@failx.de
        from: Your Name <your-email@example.com>
        content_type: text/plain
